name: Sync to Hugging Face

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync-to-huggingface:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: |
          git lfs install

      - name: Pull LFS files
        run: |
          git lfs pull

      - name: Verify LFS
        run: |
          git lfs fsck
          ls -lh "best_model FF.keras"

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force \
            https://shahd-ai:${HF_TOKEN}@huggingface.co/spaces/shahd-ai/smart-precision-agriculture \
            main
